1steps

diff --git a/.github/workflows/azure-static-web-apps-salmon-meadow-0794cac03.yml b/.github/workflows/azure-static-web-apps-salmon-meadow-0794cac03.yml
--- a/.github/workflows/azure-static-web-apps-salmon-meadow-0794cac03.yml
+++ b/.github/workflows/azure-static-web-apps-salmon-meadow-0794cac03.yml
@@ -32,6 +32,15 @@ jobs:
                const coredemo = require('@actions/core')
                return await coredemo.getIDToken()
            result-encoding: string
+      - name: verify           
+        run: |
+          if [ ! -f "${{ env.APP_LOCATION }}/index.html" ]; then
+          echo "❌ Error: index.html not found in ${{ env.APP_LOCATION }}"
+          exit 1
+          else
+          echo "✅ index.html found in ${{ env.APP_LOCATION }}"
+          fi
+
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
@@ -45,6 +54,7 @@ jobs:
           output_location: "." # Built app content directory - optional
           github_id_token: ${{ steps.idtoken.outputs.result }}
           ###### End of Repository/Build Configurations ######
+          
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
